### ISSUE TITLE
multi-class training error

### ISSUE THREAD

**Issue by HIN0209** [rdcolema/pytorch-image-classification#1]
I enjoyed the code that worked fine with a dog-cat dataset. However, by trying 4 classes, the following error showed up. Does it look like a code problem or a CUDA issue? 

main(mode="train")
=> Starting train on 'resnet50' model
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-13-58efe71d55ef> in <module>()
----> 1 main(mode="train")

<ipython-input-12-f1fadcbeed52> in main(mode, resume)
    104 
    105             # train for one epoch
--> 106             train(train_loader, model, criterion, optimizer, epoch)
    107 
    108             # evaluate on validation set

<ipython-input-4-d566ddbd645c> in train(train_loader, model, criterion, optimizer, epoch)
     22 
     23         # measure accuracy and record loss
---> 24         prec1, prec1 = accuracy(y_pred.data, target, topk=(1, 1))
     25         losses.update(loss.data[0], images.size(0))
     26         acc.update(prec1[0], images.size(0))

<ipython-input-9-1a0afbe7c4c4> in accuracy(y_pred, y_actual, topk)
     18     res = []
     19     for k in topk:
---> 20         correct_k = correct[:k].view(-1).float().sum(0)
     21         res.append(correct_k.mul_(100.0 / batch_size))
     22 

RuntimeError: cuda runtime error (59) : device-side assert triggered at /b/wheel/pytorch-src/torch/lib/THC/generated/../generic/THCTensorMathReduce.cu:16

**Comment by rdcolema** [comment]
Hey @HIN0209, I'm unfamiliar with that specific error, but I do have an example using this code with slight modification for a multi-class problem. Take a look at this and see if it helps: 

https://github.com/rdcolema/nc-fish-classification/blob/master/nc_fish_classification/pytorch_model.ipynb

^^That's an 8-class model from Kaggle's fish species identification challenge, but I think you should be able to convert to 4 classes without too much trouble.

**Comment by HIN0209** [comment]
Thank you for the info. Yes, it look like what I need!
