### ISSUE TITLE
Some questions on running other modules

### ISSUE THREAD

**Issue by lizxchen** [rdcolema/pytorch-image-classification#5]
1、'VGG' object has no attribute 'module'
 2、Given input size: (128, 3, 3). Calculated output size: (1, -1, -1). Output size is too small.
what i should do?thanks a lot.

**Comment by rdcolema** [comment]
Hey, can you provide line numbers or a more verbose traceback? Just want to make sure I can see where that's happening. I'm guessing it's something with pytorch versions since I haven't updated this repo in a long time.

**Comment by lizxchen** [comment]
AttributeError                            Traceback (most recent call last)
<ipython-input-14-277c01e2c1c8> in <module>()
----> 1 main(mode="train")

<ipython-input-12-c5068c289f5a> in main(mode, resume)
     98             return
     99 
--> 100         optimizer = optim.Adam(model.module.fc.parameters(), lr, weight_decay=1e-4)
    101 
    102         for epoch in range(epochs):

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in __getattr__(self, name)
    396                 return modules[name]
    397         raise AttributeError("'{}' object has no attribute '{}'".format(
--> 398             type(self).__name__, name))
    399 
    400     def __setattr__(self, name, value):

AttributeError: 'VGG' object has no attribute 'module'

**Comment by rdcolema** [comment]
What's the output of `model_names` in the second cell? Also just to confirm, you don't have any folders or installed packages that might have a namespace conflict with VGG?
